### ISSUE TITLE
下载器助手更新到V3.5.2后 QB 报错

### ISSUE THREAD

**Issue by behinder85** [hotlcc/MoviePilot-Plugins-Third#27]
> TypeError: TorrentInfoList.__init__() missing 1 required positional argument: 'client'
           ^^^^^^^^^^^^^^^^^^^^
    return self.__class__(self)
  File "/usr/local/lib/python3.11/collections/__init__.py", line 1304, in copy
                    ^^^^^^^^^^^^^^^
    torrents_copy = torrents.copy()
  File "/app/app/plugins/downloaderhelper/__init__.py", line 2023, in __delete_batch_for_qbittorrent
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents,
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1804, in __run_for_qbittorrent
Traceback (most recent call last):
【ERROR】2024-08-27 15:00:27,750 - downloaderhelper - 下载器[qBittorrent]任务执行失败: TorrentInfoList.__init__() missing 1 required positional argument: 'client'

下载器助手更新到V3.5.2后，QB报错
![image](https://github.com/user-attachments/assets/16fe63a2-09af-46a2-8fed-993609c9e463)
以上为错误日志

**Comment by qsxazcv** [comment]
TypeError: TorrentInfoList.__init__() missing 1 required positional argument: 'client'
           ^^^^^^^^^^^^^^^^^^^^
    return self.__class__(self)
  File "/usr/local/lib/python3.11/collections/__init__.py", line 1304, in copy
                    ^^^^^^^^^^^^^^^
    torrents_copy = torrents.copy()
  File "/app/app/plugins/downloaderhelper/__init__.py", line 2023, in __delete_batch_for_qbittorrent
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents,
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1804, in __run_for_qbittorrent
Traceback (most recent call last):
【ERROR】2024-08-27 16:28:13,824 - downloaderhelper - 下载器[qBittorrent]任务执行失败: TorrentInfoList.__init__() missing 1 required positional argument: 'client'





一样的问题？

**Comment by buzidjy** [comment]
一样的问题，发现勾选“自动删种”后就会报这个错误，希望大佬修复！

**Comment by hotlcc** [comment]
已修复，升级v3.5.3
